title: Cristina's Portfolio
author: Cristina HG
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my portfolio! 

# social links
twitter_username: @_musicalnote
github_username:  @CristinaHG

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
